### ISSUE TITLE
[BUG]Could pick item from /petblock GUI

### ISSUE THREAD

**Issue by Tollainmear** [Shynixn/PetBlocks#122]
### 2. right click any skull in this GUI
![](https://raw.githubusercontent.com/Tollainmear/PicRepo/master/bugissuePics/petblocks/1.png)
### 3.press `E` or `Esc` to closing the GUI, and the skull which you are holding was drop.
![](https://raw.githubusercontent.com/Tollainmear/PicRepo/master/bugissuePics/petblocks/2.png)
### 4. Then you may pick it up
![](https://raw.githubusercontent.com/Tollainmear/PicRepo/master/bugissuePics/petblocks/3.png)

## BTW, nothing happened after I use `/petblock call` 😆

**Comment by Shynixn** [comment]
Of course this should not happend, I need to adjust the inventory event calls. Do the actions get executed, like spawning the pet? 
Oh I thought I double checked all commands.

**Comment by Shynixn** [comment]
I have fixed the GUI problem, however the petblock call command works as expected and teleports the pet to the owner if it is spawned.

**Comment by Tollainmear** [comment]
OK I will try it as soon as possible 😄

**Comment by Tollainmear** [comment]
Sorry the great fire wall block me to connect to the gist, so I have to paste exceptions here:
`[Sponge]: Error occurred while executing command 'petblock toggle' for source EntityPlayerMP['Tollainmear'/217, l='world', x=273.77, y=70.00, z=107.36]: org.spongepowered.api.entity.Transform cannot be cast to org.spongepowered.api.world.Location
java.lang.ClassCastException: org.spongepowered.api.entity.Transform cannot be cast to org.spongepowered.api.world.Location
        at com.github.shynixn.petblocks.sponge.logic.persistence.configuration.Config.allowPetSpawning(Config.kt:108) ~[Config.class:?]
        at com.github.shynixn.petblocks.sponge.logic.business.commandexecutor.PetDataCommandExecutor$ToggleCommandExecutor.onPlayerExecuteCommand(PetDataCommandExecutor.java:134) ~[PetDataCommandExecutor$ToggleCommandExecutor.class:?]
        at com.github.shynixn.petblocks.sponge.logic.business.commandexecutor.SimpleCommandExecutor.execute(SimpleCommandExecutor.java:112) ~[SimpleCommandExecutor.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2655-7.1.0-BETA-3041]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2655-7.1.0-BETA-3041]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2655-7.1.0-BETA-3041]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2655-7.1.0-BETA-3041]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2655-7.1.0-BETA-3041]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlb000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2655-7.1.0-BETA-3041]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:3977) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]`

this exception was thrown after I execute `/petblock toggle`

Considering the less readable above, you may download the txt file [here](https://github.com/Shynixn/PetBlocks/files/1945366/Exception.txt)

Besides , I found that nothing happened after I executed `/petblock call`(both client side and console shown nothing).

Using:
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-a312749
    SpongeForge: 1.12.2-2655-7.1.0-BETA-3041
    Minecraft Forge: 14.23.3.2655
    PetBlocks: Latest version in ORE

**Comment by Tollainmear** [comment]
An'BTW there would be a poor performance to opening GUI or Clicking skull in petblock GUI after we change the skin with someone‘s ID
