### ISSUE TITLE
"Bad access to protected data in getfield" when trying to toggle pet on Sponge

### ISSUE THREAD

**Issue by BrainStone** [Shynixn/PetBlocks#138]
Whenever I try to toggle the pet, I get this error:

```
> [02:42:21] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task petblocks-S-19 owned by Plugin{id=petblocks, name=PetBlocks, version=7.0.1, description=PetBlocks is a spigot and sponge plugin to use blocks and custom heads as pets in Minecraft., authors=[Shynixn], source=/home/container/./mods/plugins/PetBlocks-Sponge-7.0.1.jar}, but an error occured.
java.lang.VerifyError: Bad access to protected data in getfield
Exception Details:
Location:
com/github/shynixn/petblocks/sponge/nms/v1_12_R1/CustomGroundArmorstand.isJumping()Z @25: getfield
Reason:
Type integer (current frame, stack[1]) is not assignable to 'com/github/shynixn/petblocks/sponge/nms/v1_12_R1/CustomGroundArmorstand'
Current Frame:
bci: @25
flags: { }
locals: { 'com/github/shynixn/petblocks/sponge/nms/v1_12_R1/CustomGroundArmorstand' }
stack: { integer }
Bytecode:
0x0000000: 2ab6 033d b900 c101 009a 001a 2ab6 033d
0x0000010: 03b9 0341 0200 c001 f8b4 0344 9900 0704
0x0000020: a700 0403 ac
Stackmap Table:
same_frame(@35)
same_locals_1_stack_item_frame(@36,Integer)
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_161]
at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_161]
at com.github.shynixn.petblocks.sponge.nms.helper.PetBlockWrapper.<init>(PetBlockWrapper.kt:74) ~[PetBlockWrapper.class:?]
at com.github.shynixn.petblocks.sponge.nms.NMSRegistry.createPetBlock(NMSRegistry.java:71) ~[NMSRegistry.class:?]
at com.github.shynixn.petblocks.sponge.logic.business.controller.SpongePetBlockRepository.create(SpongePetBlockRepository.kt:49) ~[SpongePetBlockRepository.class:?]
at com.github.shynixn.petblocks.sponge.logic.business.commandexecutor.PetBlockCommandExecutor.lambda$setPetCommand$11(PetBlockCommandExecutor.java:449) ~[PetBlockCommandExecutor.class:?]
at com.github.shynixn.petblocks.sponge.logic.business.commandexecutor.PetBlockCommandExecutor.lambda$null$13(PetBlockCommandExecutor.java:489) ~[PetBlockCommandExecutor.class:?]
at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2655-7.1.0-BETA-3051]
at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2655-7.1.0-BETA-3051]
at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:70) ~[SyncScheduler.class:1.12.2-2655-7.1.0-BETA-3051]
at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.12.2-2655-7.1.0-BETA-3051]
at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.12.2-2655-7.1.0-BETA-3051]
at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_161]
at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.12.2-2655-7.1.0-BETA-3051]
at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:44) [SyncScheduler.class:1.12.2-2655-7.1.0-BETA-3051]
at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:185) [SpongeScheduler.class:1.12.2-2655-7.1.0-BETA-3051]
at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:324) [SpongeMod.class:1.12.2-2655-7.1.0-BETA-3051]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:651) [EventBus.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:589) [EventBus.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

Versions:

PetBlocks: 7.0.1
 Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-a312749
SpongeForge: 1.12.2-2655-7.1.0-BETA-3051
Minecraft Forge: 14.23.3.2655

**Comment by BrainStone** [comment]
Again this is my fault, as I put the plugin in `mods/plugins` instead of `mods/1.12.2` or just `mods`, as it is required for plugins that use ATs under SpongeForge.

**Comment by Shynixn** [comment]
Interesting issue, do you have any problems when using PetBLocks on SpongeForge? #134

**Comment by BrainStone** [comment]
As I already pointed out, it’s because I put it in the wrong folder and the ATs weren’t being loaded. And yes, I experience that too, as I pointed out in a comment in an related issue.
