### ISSUE TITLE
KotlinNullPointerException when MySQL is enabled on Sponge

### ISSUE THREAD

**Issue by BrainStone** [Shynixn/PetBlocks#140]
When I enable MySQL on Sponge, I get this exception during the plugin startup:

```
> [03:12:02] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [PetBlocks] Loading PetBlocks ...
> May 05, 2018 3:12:03 AM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: com.github.shynixn.petblocks.lib.kotlin.KotlinNullPointerException
com.github.shynixn.petblocks.lib.kotlin.KotlinNullPointerException
at com.github.shynixn.petblocks.sponge.logic.business.helper.GoogleGuiceSubBinder.initialize(GoogleGuiceSubBinder.kt:97)
at com.github.shynixn.petblocks.sponge.logic.business.helper.GoogleGuiceSubBinder.configure(GoogleGuiceSubBinder.kt:157)
at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
at com.google.inject.spi.Elements.getElements(Elements.java:110)
at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236)
at com.github.shynixn.petblocks.sponge.PetBlocksPlugin.onEnable(PetBlocksPlugin.kt:90)
at org.spongepowered.common.event.listener.GameInitializationEventListener_PetBlocksPlugin_onEnable59.handle(Unknown Source)
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335)
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:368)
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:213)
at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:244)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:720)
at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
at java.lang.Thread.run(Thread.java:748)
[03:12:03] [Server thread/ERROR] [Sponge]: Could not pass FMLInitializationEvent to Plugin{id=petblocks, name=PetBlocks, version=7.0.1, description=PetBlocks is a spigot and sponge plugin to use blocks and custom heads as pets in Minecraft., authors=[Shynixn], source=/home/container/./mods/plugins/PetBlocks-Sponge-7.0.1.jar}
com.google.inject.CreationException: Unable to create injector, see the following errors:
1) An exception was caught and reported. Message: null
at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
1 error
at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470) ~[Errors.class:1.12.2-2655-7.1.0-BETA-3051]
at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155) ~[InternalInjectorCreator.class:1.12.2-2655-7.1.0-BETA-3051]
at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[InternalInjectorCreator.class:1.12.2-2655-7.1.0-BETA-3051]
at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232) ~[InjectorImpl.class:1.12.2-2655-7.1.0-BETA-3051]
at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236) ~[InjectorImpl.class:1.12.2-2655-7.1.0-BETA-3051]
at com.github.shynixn.petblocks.sponge.PetBlocksPlugin.onEnable(PetBlocksPlugin.kt:90) ~[PetBlocksPlugin.class:?]
at org.spongepowered.common.event.listener.GameInitializationEventListener_PetBlocksPlugin_onEnable59.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2655-7.1.0-BETA-3051]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3051]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:368) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3051]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:213) [SpongeImpl.class:1.12.2-2655-7.1.0-BETA-3051]
at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:244) [SpongeMod.class:1.12.2-2655-7.1.0-BETA-3051]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278) [LoadController.class:?]
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256) [LoadController.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?]
at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:720) [Loader.class:?]
at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) [FMLServerHandler.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337) [FMLCommonHandler.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: com.github.shynixn.petblocks.lib.kotlin.KotlinNullPointerException
at com.github.shynixn.petblocks.sponge.logic.business.helper.GoogleGuiceSubBinder.initialize(GoogleGuiceSubBinder.kt:97) ~[GoogleGuiceSubBinder.class:?]
at com.github.shynixn.petblocks.sponge.logic.business.helper.GoogleGuiceSubBinder.configure(GoogleGuiceSubBinder.kt:157) ~[GoogleGuiceSubBinder.class:?]
at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[AbstractModule.class:1.12.2-2655-7.1.0-BETA-3051]
at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[Elements$RecordingBinder.class:1.12.2-2655-7.1.0-BETA-3051]
at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[Elements.class:1.12.2-2655-7.1.0-BETA-3051]
at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138) ~[InjectorShell$Builder.class:1.12.2-2655-7.1.0-BETA-3051]
at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) ~[InternalInjectorCreator.class:1.12.2-2655-7.1.0-BETA-3051]
... 41 more
```

Versions:

PetBlocks: 7.0.1
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-a312749
SpongeForge: 1.12.2-2655-7.1.0-BETA-3051
Minecraft Forge: 14.23.3.2655

**Comment by Shynixn** [comment]
Thanks for reporting, I'll check it out.

**Comment by Shynixn** [comment]
You can be sure that I already checked it when the "not-confirmed" is missing on a "bug" issue. Will be fixed next version.

**Comment by BrainStone** [comment]
Ok. Thanks. I'm just asking, because this is a blocker for me, unless there's a simple way to copy all data from the file based database to a mysql database.

**Comment by Shynixn** [comment]
Oh maybe I can find some time to upload a snapshot of the fix tomorrow. I don't think I'm going to release any plugin update next weekend.

**Comment by Shynixn** [comment]
There you go. [Download](https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/petblocks/petblocks-sponge-plugin/7.1.0-SNAPSHOT/petblocks-sponge-plugin-7.1.0-20180511.111235-1.jar).

**Comment by BrainStone** [comment]
Ok, the NPE disappeared, however now I'm getting this exception:

https://gist.github.com/BrainStone/0c58fcdb9c3957052c7440fd028afb8f

Also I did not set the host `172.18.0.3`. `172.18.0.3` is the IP of the server itself. So it seems like the issue is that the `host` setting is being ignored.

Config: 

```
 sql:
  enabled: true
  host: 'example.com'
  port: 3306
  database: 'petblocks'
  usessl: true
  username: 'petblocks'
  password: 'xxx'
```

**Comment by Shynixn** [comment]
Let's try again. [Download](https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/petblocks/petblocks-sponge-plugin/7.1.0-SNAPSHOT/petblocks-sponge-plugin-7.1.0-20180512.090046-2.jar).

**Comment by BrainStone** [comment]
Yup, working now.
