### ISSUE TITLE
KotlinNullPointerException when player with disabled pet joins

### ISSUE THREAD

**Issue by BrainStone** [Shynixn/PetBlocks#150]
When a player joins and has their pet disabled, I get this exception:

```
> [18:23:25] [pool-3-thread-9/ERROR] [Sponge]: The Scheduler tried to run the task petblocks-A-336 owned by Plugin{id=petblocks, name=PetBlocks, version=7.0.1, description=PetBlocks is a spigot and sponge plugin to use blocks and custom heads as pets in Minecraft., authors=[Shynixn], source=/home/container/mods/1.12.2/PetBlocks-Sponge-7.1.0-20180512.090046-2.jar}, but an error occured.
com.github.shynixn.petblocks.lib.kotlin.KotlinNullPointerException: null
at com.github.shynixn.petblocks.sponge.logic.persistence.configuration.Config.fixJoinDefaultPet(Config.kt:86) ~[Config.class:?]
at com.github.shynixn.petblocks.sponge.logic.business.listener.SpongePetDataListener.lambda$playerJoinEvent$5(SpongePetDataListener.java:149) ~[SpongePetDataListener.class:?]
at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2655-7.1.0-BETA-3065]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

Versions:

- PetBlocks: 7.1.0-SNAPSHOT
- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-SNAPSHOT-7d8a938
- SpongeForge: 1.12.2-2655-7.1.0-BETA-3065
- Minecraft Forge: 14.23.3.2655

**Comment by Shynixn** [comment]
This is issue is related to #149 . Should be fixed together.

**Comment by BrainStone** [comment]
I thought so. Just based on the stack trace alone.

Well I’m not sure if this is the best place to ask, but do you happen to have Discord and maybe even a Discord server? I think it’s the best place to ask quick question and have a chat etc.

**Comment by BrainStone** [comment]
From looking at it, it seems like `petMeta` is null here: https://github.com/Shynixn/PetBlocks/blob/9e524b811f477810f03533b92217df78028cef32/petblocks-sponge-plugin/src/main/java/com/github/shynixn/petblocks/sponge/logic/persistence/configuration/Config.kt#L86

Would probably be a smart idea to make a null check and assign a default object.

**Comment by Shynixn** [comment]
Thanks for your support, I'll decide it in a few days.

**Comment by Shynixn** [comment]
@BrainStone I have thought about a discord server. I'm not going to setup one by myself however if you like you can create one and I'll be active on it. Also, I can add it to all project pages afterwards.
