### ISSUE TITLE
IllegalArgumentException: Entity is already unregisterd!

### ISSUE THREAD

**Issue by BrainStone** [Shynixn/PetBlocks#154]
When shutting down the server the following exception is thrown:

```
java.lang.IllegalArgumentException: Entity is already unregisterd!
at com.github.shynixn.petblocks.sponge.nms.v1_12_R1.CustomEntityRegistry.unregister(CustomEntityRegistry.java:76) ~[CustomEntityRegistry.class:?]
at com.github.shynixn.petblocks.sponge.nms.NMSRegistry.unregisterCustomEntities(NMSRegistry.java:84) ~[NMSRegistry.class:?]
at com.github.shynixn.petblocks.sponge.PetBlocksPlugin.onDisable(PetBlocksPlugin.kt:126) [PetBlocksPlugin.class:?]
at org.spongepowered.common.event.listener.GameStoppingServerEventListener_PetBlocksPlugin_onDisable76.handle(Unknown Source) [?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:369) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:407) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:391) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:213) [SpongeImpl.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:244) [SpongeMod.class:1.12.2-2655-7.1.0-BETA-3065]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278) [LoadController.class:?]
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256) [LoadController.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?]
at net.minecraftforge.fml.common.Loader.serverStopping(Loader.java:790) [Loader.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopping(FMLCommonHandler.java:307) [FMLCommonHandler.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:531) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

Versions:

- PetBlocks: 7.1.0-SNAPSHOT
- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-SNAPSHOT-7d8a938
- SpongeForge: 1.12.2-2655-7.1.0-BETA-3065
- Minecraft Forge: 14.23.3.2655

**Comment by Shynixn** [comment]
The forge entity is not registered and spawns as an invisible "invalid" entity from a client's view. I have forgotten to the remove the additional check. I'll fix this when I take a look at your pull request.
