### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vr6syncro** [Shynixn/PetBlocks#158]
`[21:00:28 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'petblocks' in com.github.shynixn.petblocks.bukkit.logic.business.commandexecutor.PetBlockCommandExecutor(petblocks)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-3d850ec-809c399]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: com/github/shynixn/petblocks/bukkit/logic/business/helper/ChatBuilderExtensionKt
        at com.github.shynixn.petblocks.bukkit.logic.business.commandexecutor.PetBlockCommandExecutor.sendMessage(PetBlockCommandExecutor.java:234) ~[?:?]
        at com.github.shynixn.petblocks.bukkit.logic.business.commandexecutor.PetBlockCommandExecutor.onCommandSenderExecuteCommand(PetBlockCommandExecutor.java:183) ~[?:?]
        at com.github.shynixn.petblocks.bukkit.logic.business.commandexecutor.SimpleCommandExecutor$UnRegistered.execute(SimpleCommandExecutor.java:289) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-3d850ec-809c399]
        ... 14 more
>plugman unload  petblocks`

**Comment by Shynixn** [comment]
This has to do with unloading and loading the plugin PetBlocks during RunTime. As there can be any kind of unexpected action I cannot resolve this.
