### ISSUE TITLE
Entity Checking exception. Harmless but throws exception.

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/PetBlocks#195]
* Refactor messages to sponge.

java.lang.IllegalArgumentException: Player has to be a BukkitPlayer!
        at com.github.shynixn.petblocks.sponge.logic.business.service.CarryPetServiceImpl.isCarryingPet(CarryPetServiceImpl.kt:159) ~[CarryPetServiceImpl.class:?]
        at com.github.shynixn.petblocks.sponge.logic.business.listener.CarryPetListener.onPlayerDeathEvent(CarryPetListener.kt:131) ~[CarryPetListener.class:?]
        at org.spongepowered.common.event.listener.DeathListener_CarryPetListener_onPlayerDeathEvent22.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:347) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:231) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callDestructEntityEventDeath(SpongeCommonEventFactory.java:947) [SpongeCommonEventFactory.class:1.12.2-2705-7.1.0-BETA-3361]
        at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:3330) [vp.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3623) [vp.class:?]
        at net.minecraft.entity.EntityLivingBase.func_180430_e(EntityLivingBase.java:1318) [vp.class:?]

**Comment by X00LA** [comment]
Hi,
I also hav this error on Sponge-Forge 1.12.2-2768-7.4.1.

`java.lang.IllegalArgumentException: Player has to be a BukkitPlayer!
at com.github.shynixn.petblocks.sponge.logic.business.service.CarryPetServiceImpl.isCarryingPet(CarryPetServiceImpl.kt:159) ~[CarryPetServiceImpl.class:?]
at com.github.shynixn.petblocks.sponge.logic.business.listener.CarryPetListener.onPlayerDeathEvent(CarryPetListener.kt:131) ~[CarryPetListener.class:?]
at org.spongepowered.common.event.listener.DeathListener_CarryPetListener_onPlayerDeathEvent54.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2768-7.1.4]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.4]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:347) [SpongeModEventManager.class:1.12.2-2768-7.1.4]
at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435) [SpongeModEventManager.class:1.12.2-2768-7.1.4]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2768-7.1.4]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:248) [SpongeImpl.class:1.12.2-2768-7.1.4]
at org.spongepowered.common.event.SpongeCommonEventFactory.callDestructEntityEventDeath(SpongeCommonEventFactory.java:920) [SpongeCommonEventFactory.class:1.12.2-2768-7.1.4]
at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:3330) [vp.class:?]
at net.minecraft.entity.passive.EntityTameable.func_70645_a(SourceFile:213) [wb.class:?]
at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3623) [vp.class:?]
at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:66) [zv.class:?]
at net.minecraft.entity.passive.EntityWolf.func_70097_a(EntityWolf.java:347) [aam.class:?]
at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:234) [vp.class:?]
at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208) [vq.class:?]
at net.minecraft.entity.Entity.func_70071_h_(Entity.java:389) [vg.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2089) [vp.class:?]
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) [vq.class:?]
at net.minecraft.entity.passive.EntityWolf.func_70071_h_(EntityWolf.java:230) [aam.class:?]
at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:157) [TrackingUtil.class:1.12.2-2768-7.1.4]
at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zma000(WorldServer.java:2982) [oo.class:?]
at net.minecraft.world.World.func_72866_a(World.java:4157) [amu.class:?]
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) [oo.class:?]
at net.minecraft.world.World.func_72870_g(World.java:1955) [amu.class:?]
at net.minecraft.world.World.func_72939_s(World.java:6605) [amu.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2295) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

Hope you can fix this.

Thank you

**Comment by Shynixn** [comment]
Please  use the latest snapshot version from my discord server. The next release version of Petblocks still takes a while.
