### ISSUE TITLE
Filtering causes shutdown crash

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/PetBlocks#22]
[19:06:31 INFO]: Saving chunks for level 'world'/overworld
[19:06:32 INFO]: Saving chunks for level 'world_nether'/the_nether
[19:06:32 INFO]: Saving chunks for level 'world_the_end'/the_end
>2017-07-25 19:06:32,368 pool-1-thread-1 ERROR Caught exception executing shutdown hook null java.lang.AbstractMethodError: com.github.shynixn.petblocks.lib.Filtering$1.stop()V
    at org.apache.logging.log4j.core.filter.CompositeFilter.stop(CompositeFilter.java:145)
    at org.apache.logging.log4j.core.filter.AbstractFilterable.stop(AbstractFilterable.java:163)
    at org.apache.logging.log4j.core.filter.AbstractFilterable.stop(AbstractFilterable.java:150)
    at org.apache.logging.log4j.core.config.AbstractConfiguration.stop(AbstractConfiguration.java:315)
    at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:351)
    at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:279)
    at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry$RegisteredCancellable.run(DefaultShutdownCallbackRegistry.java:109)
    at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:74)
    at java.lang.Thread.run(Unknown Source)
    
Press any key to continue . . .

**Comment by Shynixn** [comment]
Should be fixed in the latest snapshot petblocks-6.0.2-20170805.111214-2-jar-with-dependencies.jar

**Comment by Shynixn** [comment]
Error still present but cannot be recreated by myself. Testing it.

https://pastebin.com/raw/42hBnaCH

**Comment by Shynixn** [comment]
Fixed in latest snapshot petblocks-6.1.0-20170827.102807-2-jar-with-dependencies.jar
