### ISSUE TITLE
Error enabling Pet on SpongeForge

### ISSUE THREAD

**Issue by g0d-gam3** [Shynixn/PetBlocks#224]
Hi,

I have encountered this issue when running the following and trying to enable my pet.

- PetBlocks 7.3.0
- SpongeForge: 1.12.2-2768-7.1.5
- SpongeAPI: 7.1.0-366290f8

```
[02:48:17] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task petblocks-S-361 owned by Plugin{id=petblocks, name=PetBlocks, version=7.3.0, description=PetBlocks is a spigot and sponge plugin to use blocks and custom heads as pets in Minecraft., authors=[Shynixn], source=/home/production/interactions/./mods/plugins/PetBlocks-Sponge.jar}, but an error occured.
java.lang.RuntimeException: Cannot create petblock.
        at com.github.shynixn.petblocks.sponge.nms.NMSRegistry.createPetBlock(NMSRegistry.java:73) ~[NMSRegistry.class:?]
        at com.github.shynixn.petblocks.sponge.logic.business.controller.SpongePetBlockRepository.create(SpongePetBlockRepository.kt:49) ~[SpongePetBlockRepository.class:?]
        at com.github.shynixn.petblocks.sponge.logic.business.listener.SpongePetDataListener.setPetBlock(SpongePetDataListener.java:335) ~[SpongePetDataListener.class:?]
        at com.github.shynixn.petblocks.sponge.logic.business.listener.SpongePetDataListener.handleClick(SpongePetDataListener.java:164) ~[SpongePetDataListener.class:?]
        at com.github.shynixn.petblocks.sponge.logic.business.listener.SpongePetDataListener.lambda$null$1(SpongePetDataListener.java:109) ~[SpongePetDataListener.class:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_161]
        at com.github.shynixn.petblocks.sponge.logic.business.listener.SpongePetDataListener.lambda$null$2(SpongePetDataListener.java:109) ~[SpongePetDataListener.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2768-7.1.5]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2768-7.1.5]
        at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2768-7.1.5]
        at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:183) ~[SchedulerBase.class:1.12.2-2768-7.1.5]
        at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:169) ~[SchedulerBase.class:1.12.2-2768-7.1.5]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_161]
        at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2768-7.1.5]
        at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2768-7.1.5]
        at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:362) [SpongeMod.class:1.12.2-2768-7.1.5]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_785_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:747) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:697) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_161]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_161]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_161]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_161]
        at com.github.shynixn.petblocks.core.logic.business.helper.ReflectionUtils.invokeConstructor(ReflectionUtils.java:65) ~[ReflectionUtils.class:?]
        at com.github.shynixn.petblocks.sponge.nms.helper.PetBlockWrapper.<init>(PetBlockWrapper.kt:85) ~[PetBlockWrapper.class:?]
        at com.github.shynixn.petblocks.sponge.nms.NMSRegistry.createPetBlock(NMSRegistry.java:71) ~[NMSRegistry.class:?]
        ... 24 more
Caused by: java.lang.IllegalAccessError
        at com.github.shynixn.petblocks.sponge.nms.v1_12_R1.CustomRabbit.<init>(CustomRabbit.java:39) ~[CustomRabbit.class:?]
        at com.github.shynixn.petblocks.sponge.nms.v1_12_R1.CustomGroundArmorstand.spawn(CustomGroundArmorstand.java:291) ~[CustomGroundArmorstand.class:?]
        at com.github.shynixn.petblocks.sponge.nms.v1_12_R1.CustomGroundArmorstand.<init>(CustomGroundArmorstand.java:92) ~[CustomGroundArmorstand.class:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_161]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_161]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_161]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_161]
        at com.github.shynixn.petblocks.core.logic.business.helper.ReflectionUtils.invokeConstructor(ReflectionUtils.java:65) ~[ReflectionUtils.class:?]
        at com.github.shynixn.petblocks.sponge.nms.helper.PetBlockWrapper.<init>(PetBlockWrapper.kt:85) ~[PetBlockWrapper.class:?]
        at com.github.shynixn.petblocks.sponge.nms.NMSRegistry.createPetBlock(NMSRegistry.java:71) ~[NMSRegistry.class:?]
        ... 24 more

```

Any help or fix for this would be much appreciated :)

Thanks!

**Comment by Shynixn** [comment]
Hi, 

Unfortunately, I cannot really tell why this happens on some SpongeForge server or not as sometimes the access transformers do not get applied. Please see #206 .
