### ISSUE TITLE
PetBlocks spam on console

### ISSUE THREAD

**Issue by Azriael2** [Shynixn/PetBlocks#246]
Hi there. I'm not best at reading errors, but I guess it has something to do with petblocks and bskyblock. I'm getting following spam on console:

`[21:10:11 WARN]: [PetBlocks] Failed shouldGoalBeExecuted.
java.lang.IllegalArgumentException: Cannot measure distance between BSkyBlock_world and spawn
        at org.bukkit.Location.distanceSquared(Location.java:473) ~[skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at org.bukkit.Location.distance(Location.java:456) ~[skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at com.github.shynixn.petblocks.bukkit.logic.business.service.EntityServiceImpl$5$2.invoke(EntityServiceImpl.kt:174) ~[PetBlocks-Bukkit.jar:?]
        at com.github.shynixn.petblocks.bukkit.logic.business.service.EntityServiceImpl$5$2.invoke(EntityServiceImpl.kt:53) ~[PetBlocks-Bukkit.jar:?]
        at com.github.shynixn.petblocks.core.logic.business.proxy.PathfinderProxyImpl.shouldGoalBeExecuted(PathfinderProxyImpl.kt:72) [PetBlocks-Bukkit.jar:?]
        at com.github.shynixn.petblocks.bukkit.logic.business.nms.v1_13_R2.Pathfinder.a(Pathfinder.kt:38) [PetBlocks-Bukkit.jar:?]
        at net.minecraft.server.v1_13_R2.PathfinderGoalSelector.doTick(SourceFile:94) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.EntityInsentient.doTick(EntityInsentient.java:659) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.EntityLiving.movementTick(EntityLiving.java:2254) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.EntityInsentient.movementTick(EntityInsentient.java:510) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.EntityAgeable.movementTick(EntityAgeable.java:145) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.EntityAnimal.movementTick(EntityAnimal.java:27) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.EntityRabbit.movementTick(EntityRabbit.java:182) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2098) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.java:248) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1331) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.World.g(World.java:1298) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1132) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:583) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:968) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [skyblock-spigot.jar:git-Spigot-f09662d-3697519]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]`

**Comment by Shynixn** [comment]
Thanks for reporting, I will fix this.

**Comment by MorkaZ** [comment]
Hope this will be fixed fast :(

**Comment by Shynixn** [comment]
As I mentioned on my discord server, I'm quite busy but I will work on it. 
The referenced commit probably fixes this error,  I wrote this on a train. 

Can you please take a look at the snapshot published along with this commit? You can look for it in the snapshot repository mentioned in the README or directly download it from the snapshot bot on my discord server.
