### ISSUE TITLE
EntityRegistry prints error when being used in some cases

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/PetBlocks#25]
[PetBlocks] Disabling PetBlocks v6.0.1
[03:06:43 WARN]: Failed to unregister entity!
java.lang.NoSuchFieldException: c
at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_144]
at com.github.shynixn.petblocks.lib.LightRegistry$WrappedEntityRegistry.unregister(LightRegistry.java:106) ~[PetBlocks.jar:?]
at com.github.shynixn.petblocks.lib.LightRegistry.unregister(LightRegistry.java:47) [PetBlocks.jar:?]
at com.github.shynixn.petblocks.business.bukkit.nms.NMSRegistry.unregisterAll(NMSRegistry.java:60) [PetBlocks.jar:?]
at com.github.shynixn.petblocks.business.bukkit.PetBlocksPlugin.onDisable(PetBlocksPlugin.java:43) [PetBlocks.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) [spigot-1.12.jar:git-Spigot-99c2a37-9a82fa7]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.12.jar:git-Spigot-99c2a37-9a82fa7]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:421) [spigot-1.12.jar:git-Spigot-99c2a37-9a82fa7]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:414) [spigot-1.12.jar:git-Spigot-99c2a37-9a82fa7]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:346) [spigot-1.12.jar:git-Spigot-99c2a37-9a82fa7]
at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:464) [spigot-1.12.jar:git-Spigot-99c2a37-9a82fa7]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612) [spigot-1.12.jar:git-Spigot-99c2a37-9a82fa7]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

**Comment by Shynixn** [comment]
Fixed in latest snapshot petblocks-6.0.2-20170805.111214-2-jar-with-dependencies.jar
