### ISSUE TITLE
Broken AI (1.13.2.)

### ISSUE THREAD

**Issue by wildmaster84** [Shynixn/PetBlocks#264]
The AI does not process correctly in 1.13.2

Error Log:
[20:27:59] [Server thread/WARN]: [PetBlocks] Failed to execute tick.
java.lang.NoSuchFieldException: modifiers
	at java.lang.Class.getDeclaredField(Class.java:2417) ~[?:?]
	at com.github.shynixn.petblocks.core.logic.business.extension.ExtensionMethodKt.removeFinalModifier(ExtensionMethod.kt:68) ~[?:?]
	at com.github.shynixn.petblocks.bukkit.logic.business.nms.v1_13_R2.NMSPetRabbit.clearAIGoals(NMSPetRabbit.kt:115) ~[?:?]
	at com.github.shynixn.petblocks.bukkit.logic.business.nms.v1_13_R2.NMSPetRabbit.<init>(NMSPetRabbit.kt:47) ~[?:?]
	at com.github.shynixn.petblocks.bukkit.logic.business.nms.v1_13_R2.NMSPetArmorstand.spawnHitBox(NMSPetArmorstand.kt:161) ~[?:?]
	at com.github.shynixn.petblocks.bukkit.logic.business.nms.v1_13_R2.NMSPetArmorstand.doTick(NMSPetArmorstand.kt:216) ~[?:?]
	at net.minecraft.server.v1_13_R2.EntityLiving.movementTick(EntityLiving.java:2338) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2135) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.EntityArmorStand.tick(EntityArmorStand.java:585) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1561) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1528) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1339) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:599) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1107) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-637]
	at java.lang.Thread.run(Thread.java:835) [?:?]

**Comment by LazoYoung** [comment]
Confirm you are using spigot?

**Comment by wildmaster84** [comment]
Im using Paper, a fork of spigot.

**Comment by Shynixn** [comment]
Are you using the latest spigot/paper 1.13.2 build @wildmaster84 ?

**Comment by wildmaster84** [comment]
Im using build 637

**Comment by Shynixn** [comment]
@wildmaster84 Are you using Java 12? If possible can you tell me your full Java version.

**Comment by wildmaster84** [comment]
Im using Java 12.0.1 build 12.0.1+12

**Comment by Shynixn** [comment]
Thank you. I'll publish a release with a fix today.
