### ISSUE TITLE
Player is no longer online error when using SpongeForge 1.12.2-2838. Does not appear in the stable version.

### ISSUE THREAD

**Issue by eviqnn** [Shynixn/PetBlocks#280]
So, upon installing the plugin on my server. I've encountered a small issue. You cannot actually spawn/call them!

Heres the log that gets printed to the console whenever I do /petblock

`[03:55:58] [Server thread/INFO] [nucleus]: ShadyEviqnn ran the command: /petblock call
[03:55:58] [Server thread/WARN] [petblocks]: Failed to spawn pet.
java.lang.IllegalArgumentException: Player is no longer online!
        at com.github.shynixn.petblocks.sponge.logic.business.service.ProxyServiceImpl.findPlayerProxyObjectFromUUID(ProxyServiceImpl.kt:77) ~[ProxyServiceImpl.class:?]
        at com.github.shynixn.petblocks.sponge.logic.business.service.EntityServiceImpl.spawnPetProxy(EntityServiceImpl.kt:159) ~[EntityServiceImpl.class:?]
        at com.github.shynixn.petblocks.core.logic.business.service.PetServiceImpl.getOrSpawnPetFromPlayer(PetServiceImpl.kt:86) [PetServiceImpl.class:?]
        at com.github.shynixn.petblocks.core.logic.business.service.PetActionServiceImpl.callPet(PetActionServiceImpl.kt:93) [PetActionServiceImpl.class:?]
        at com.github.shynixn.petblocks.core.logic.business.commandexecutor.PlayerPetActionCommandExecutorImpl.onPlayerExecuteCommand(PlayerPetActionCommandExecutorImpl.kt:50) [PlayerPetActionCommandExecutorImpl.class:?]
        at com.github.shynixn.petblocks.sponge.logic.business.proxy.CommandProxyImpl.execute(CommandProxyImpl.kt:70) [CommandProxyImpl.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) [CommandSpec.class:1.12.2-2838-7.1.7-RC3890]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) [SimpleDispatcher.class:1.12.2-2838-7.1.7-RC3890]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:338) [SpongeCommandManager.class:1.12.2-2838-7.1.7-RC3890]
        at net.minecraft.command.ServerCommandManager.executeCommand(SourceFile:665) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:962) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:941) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:191) [PacketPhaseUtil.class:1.12.2-2838-7.1.7-RC3890]
        at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zko000(SourceFile:540) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_221]
        at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.1.7-RC3890]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(MinecraftServer.java:4715) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]`

**Comment by eviqnn** [comment]
Just opened up a brand new server to ensure it was not a plugin-related issue; it is not.

Using: 
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-9067212f0
    Sponge: 1.12.2-7.1.7-SNAPSHOT
    SpongeForge: 1.12.2-2838-7.1.7-RC3890
    Minecraft Forge: 14.23.5.2838
    JVM: 1.8.0_221/64-bit (Oracle Corporation)
    OS: Windows 10 (10.0/amd64)
    PetBlocks: 8.7.0

**Comment by Shynixn** [comment]
Hi @eviqnn!

I have tested PetBlocks with your configuration and I can confirm that PetBlocks does indeed not work.

However, PetBlocks-Sponge does **only** support the latest recommend and stable build of SpongeForge. This is also stated on https://shynixn.github.io/PetBlocks/build/html/gettingstarted/installing.html. 
Please install 1.12.2-2825-7.1.6 instead if you want to use PetBlocks-Sponge. 

This issue may or may not be an issue of SpongeForge itself so I would like to leave this issue open and check it again when the recommend SpongeForge changes. 

Thank you for reporting!

**Comment by eviqnn** [comment]
@Shynixn Wow- thanks for the super quick response-
PetBlocks has a LOT of potential!- I love the GUI and how simple it is to use!

I'll be sure to test this on Recommended~ thanks for the help and good luck in your journey~

Keep doing what you do!
You have a PayPal I could donate to? I would love to be a patron but I cannot pay monthly.

**Comment by eviqnn** [comment]
Trying to find a version between recommended -> latest that works with both GriefPrevention and PetBlocks~ I'll let you know if i'm successful or not.

**Comment by Shynixn** [comment]
@eviqnn 

Thank you for your kind reply :)
Sponge is always a bit difficult concerning compatibility. Hopefully you can find a configuration. 

Hm... thank you for considering donating to me! I currently do not maintain the patreon page anyway but you can cancel the subscription immediatly after paying. Message me on my discord server if you like the patreon role afterwards.

**Comment by HeberonYT** [comment]
@Shynixn I understand that you do not want to upgrade to each version of sponge, but you must also understand that not everyone can use the recommended version of sponge, much less when it comes to a Minecraft Network. Even the sponge members themselves do not respond to support requests if you do not use the latest version.
I just wish you can update to the latest changes, sponge is updated quite quickly but not all changes affect your plugin.

**Comment by eviqnn** [comment]
@HeberonYT 's comment has reminded me:
There is no version compatible between Recommended -> Latest that supports both PetBlocks and GriefPrevention, considering GP is a widely used plugin, this should be considered.

**Comment by HeberonYT** [comment]
The same with sponga, I did not have the habit of updating to each version, but it was necessary when you discover that patches are made for glitch dupe, performance or corrections in the base code such as the one that corrected a problem with the fakePlayers, which broke the functions from PetBlocks as I think.

**Comment by HeberonYT** [comment]
By the way, GP is a dead project, we will soon have to migrate to a new complement. I don't want to think about what will happen with PetBlocks when the day comes.

**Comment by Shynixn** [comment]
> I just wish you can update to the latest changes, sponge is updated quite quickly but not all changes affect your plugin.

Hi @HeberonYT. This is true but there are multiple "latest sponge" versions a week. It is impossible to keep track of this in my free time. So I simply state that only the recommend version is supported. 

Well PetBlocks depends on lot of parts of the SpongeAPI: Entities, Sound, Particles, Inventory and there are lots of builds where some minor parts in Sponge are broken. Getting frustrated each time the API changes (which should not change very often per design) is very annoying. 

> such as the one that corrected a problem with the fakePlayers, which broke the functions from PetBlocks as I think. 

As API user I do not care if they improved the performance or changed the implementation.  However,  I care and expect to get the same output with the same input otherwise they should add a new function and deprecate the old one. (source: literally every API design guide)

Thank you for the function hint 👍 

> By the way, GP is a dead project, we will soon have to migrate to a new complement. I don't want to think about what will happen with PetBlocks when the day comes

That's a shame if you do not like to use PetBlocks anymore. :/

Last but not least if many people really need to use the latest version I can always make an exception. Would you like me to fix it soon @HeberonYT @eviqnn?

**Comment by eviqnn** [comment]
@Shynixn
As a developer myself; I respect that you do not want to have to update every single update that comes out hour after hour everyday.

It would be much appreciated if you could update PetBlocks as I am interested in what this plugin has to offer. 

I cannot use petBlocks right now, because there isn’t a version between Grief Prevention and PetBlock that is compatible with both.

GriefPrevention is obviously quite an important plugin; as it provides players and administrators a way of protecting spawn and claims.

Although, as a developer myself; please keep in mind that these latest sponge releases usually fix some big bugs- like performance issues, dupes etc like Hebe said above.

Thanks for the quick response as always! ❤️

**Comment by Shynixn** [comment]
Can you please confirm if it is working now @eviqnn?

Snapshot:
https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/petblocks/petblocks-sponge-plugin/8.7.0-SNAPSHOT/petblocks-sponge-plugin-8.7.0-20190825.164144-10.jar

**Comment by eviqnn** [comment]
@Shynixn It does indeed work! Thanks for the super quick response!
When testing- I have noticed that the pet (when put on players head) is kinda floating just 1 block above the actual players head.

Thanks for the awesome effort!

**Comment by Shynixn** [comment]
Nice, thank you!

Yes, it is normally not possible to modify the riding offset but I think there might be a way in the future.
