### ISSUE TITLE
Type-cast exception is raised while plugin is booting up.

### ISSUE THREAD

**Issue by LazoYoung** [Shynixn/PetBlocks#383]
```
> [14:27:04 INFO]: [PetBlocks] found dependency [HeadDatabase].
> [14:27:04 INFO]: [PetBlocks] successfully loaded dependency [HeadDatabase] 4.12.2.
> [14:27:04 ERROR]: Error occurred while enabling PetBlocks v8.17.1 (Is it up to date?)
com.github.shynixn.petblocks.lib.kotlin.TypeCastException: null cannot be cast to non-null type org.bukkit.configuration.MemorySection
at com.github.shynixn.petblocks.bukkit.PetBlocksPlugin.onEnable(PetBlocksPlugin.kt:182) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Spigot.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

Latest version of petblocks belongs to this issue.
It's reported from our discord community.

**Comment by Shynixn** [comment]
Thanks for reporting but this is an ordinary config parse error.
