### ISSUE TITLE
Error after the update

### ISSUE THREAD

**Issue by STEINTALCHRIS** [Shynixn/PetBlocks#443]
The GUI no longer works after the update.
Without a GUI, petblocks cannot be used by our players because there are too many commands

> [15:58:49 INFO]: STEINTALCHRIS issued server command: /petblock gui
[15:58:49 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'petblock gui' in com.github.shynixn.petblocks.bukkit.logic.business.proxy.CommandProxyImpl(petblock)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.16.3.jar:git-Paper-206]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-206]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.github.shynixn.petblocks.lib.kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.Map<kotlin.String, kotlin.Any>
        at com.github.shynixn.petblocks.core.logic.business.service.GUIItemLoadServiceImpl.findGUIItemCollection(GUIItemLoadServiceImpl.kt:144) ~[?:?]
        at com.github.shynixn.petblocks.core.logic.business.service.GUIServiceImpl.renderPage(GUIServiceImpl.kt:313) ~[?:?]
        at com.github.shynixn.petblocks.core.logic.business.service.GUIServiceImpl.open(GUIServiceImpl.kt:233) ~[?:?]
        at com.github.shynixn.petblocks.core.logic.business.commandexecutor.PlayerPetActionCommandExecutorImpl.onPlayerExecuteCommand(PlayerPetActionCommandExecutorImpl.kt:99) ~[?:?]
        at com.github.shynixn.petblocks.bukkit.logic.business.proxy.CommandProxyImpl.execute(CommandProxyImpl.kt:66) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-206]
        ... 17 more
>

**Comment by Shynixn** [comment]
It seems like PetBlocks does not find "gui" in your config.yml. Can you share your config.yml somehow? (Discord Private Message?)
