### ISSUE TITLE
1.9 itemHand access fails in 1.8.8

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/PetBlocks#45]
`20:24:49] [Server thread/WARN]: [PetBlocks] Failed to gather item in 19 hand.
java.lang.NoSuchMethodException: org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.getItemInHand()
	at java.lang.Class.getDeclaredMethod(Class.java:2130) ~[?:1.8.0_141]
	at com.github.shynixn.petblocks.bukkit.lib.ReflectionUtils.invokeMethodByObject(ReflectionUtils.java:167) ~[PetBlocks.jar:?]
	at com.github.shynixn.petblocks.bukkit.lib.ReflectionUtils.invokeMethodByObject(ReflectionUtils.java:139) ~[PetBlocks.jar:?]
	at com.github.shynixn.petblocks.bukkit.nms.NMSRegistry.getItemInHand19(NMSRegistry.java:161) [PetBlocks.jar:?]
	at com.github.shynixn.petblocks.bukkit.logic.business.listener.PetBlockListener.entityRightClickEvent(PetBlockListener.java:227) [PetBlocks.jar:?]
	at sun.reflect.GeneratedMethodAccessor344.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1315) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at de.robingrether.idisguise.management.channel.InjectedPlayerConnection183.a(InjectedPlayerConnection183.java:53) [iDisguise.jar:?]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]`

**Comment by Shynixn** [comment]
Fixed in latest snapshot petblocks-bukkit-plugin-6.3.0-20171021.105221-4-jar-with-dependencies.jar
