### ISSUE TITLE
Bug on Spigot 1.12.2.

### ISSUE THREAD

**Issue by TheIntelloBox** [Shynixn/PetBlocks#53]
[21:32:20] [Server thread/WARN]: Failed to unregister entity! 
java.lang.NoSuchFieldException: c
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_72]
	at com.github.shynixn.petblocks.lib.LightRegistry$WrappedEntityRegistry.unregister(LightRegistry.java:105) ~[PetBlocks.jar:?]
	at com.github.shynixn.petblocks.lib.LightRegistry.unregister(LightRegistry.java:46) [PetBlocks.jar:?]
	at com.github.shynixn.petblocks.business.bukkit.nms.NMSRegistry.unregisterAll(NMSRegistry.java:60) [PetBlocks.jar:?]
	at com.github.shynixn.petblocks.business.bukkit.PetBlocksPlugin.onDisable(PetBlocksPlugin.java:51) [PetBlocks.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.disablePlugin(PerWorldPluginLoader.java:140) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:421) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:414) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:352) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:465) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:613) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by Shynixn** [comment]
Checking and fixing it, thanks for reporting!

It has something todo with cleaning up the entity registry and different versions of minecraft. 
You can still use PetBlocks as usual as this does only have an impact if you spam the /reload command on your server.

**Comment by TheIntelloBox** [comment]
Is this possible that this cause that my map is corrupted ? Because the map where we use the petblocks has 541 chunks corrupted. xD

**Comment by Shynixn** [comment]
Interesting, custom entities tend to cause these kind of problems. How did you find out (tool, log, etc..) that these chunks are corrupted and does it state a reason?

**Comment by TheIntelloBox** [comment]
My server always crashed so I contacted my host and they said that the map was corrupted. So I downloaded Minecraft Region Fixer and the tool found that there was 541 chunks corrupted.

**Comment by Shynixn** [comment]
Thanks, I'll try to crash my testing environment on purpose and see if any chunks could get corrupted.

I'm really sorry for any inconvenience caused :/

**Comment by TheIntelloBox** [comment]
Wait, that's just an hypotesis, I don't know if it's the fault of PetBlocks, but there's a chance.

**Comment by Shynixn** [comment]
I cannot recreate this issue, however I finally patched the old EntityRegistry which was deprecated for months.

Please download the [latest snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/petblocks/petblocks-bukkit-plugin/6.3.1-SNAPSHOT/petblocks-bukkit-plugin-6.3.1-20171107.173330-3-jar-with-dependencies.jar) and check if your problem is resolved. As the config did not change you only need to override the PetBlocks.jar in your plugin folder.

**Comment by Shynixn** [comment]
@TheIntelloBox  Any related problems since the last release?

**Comment by Shynixn** [comment]
Author was not responding for over a month --> issue gets closed
