### ISSUE TITLE
Particleeffects crash when using PaperSpigot

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/PetBlocks#56]
ava.lang.NoSuchFieldException: playerConnection 06.11 11:41:16 [Server] INFO at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_91] 06.11 11:41:16 [Server] INFO at com.github.shynixn.petblocks.bukkit.logic.persistence.entity.ParticleEffectData.sendPacket(ParticleEffectData.java:728) ~[PetBlocks.jar:?] 06.11 11:41:16 [Server] INFO at com.github.shynixn.petblocks.bukkit.logic.persistence.entity.ParticleEffectData.applyTo(ParticleEffectData.java:620) [PetBlocks.jar:?] 06.11 11:41:16 [Server] INFO at com.github.shynixn.petblocks.bukkit.logic.persistence.entity.ParticleEffectData.apply(ParticleEffectData.java:555) [PetBlocks.jar:?] 06.11 11:41:16 [Server] INFO at com.github.shynixn.petblocks.bukkit.nms.helper.PetBlockHelper.doTickSounds(PetBlockHelper.java:198) [PetBlocks.jar:?] 06.11 11:41:16 [Server] INFO at com.github.shynixn.petblocks.bukkit.nms.helper.PetBlockHelper.doTick(PetBlockHelper.java:139) [PetBlocks.jar:?] 06.11 11:41:16 [Server] INFO at com.github.shynixn.petblocks.bukkit.nms.v1_12_R1.CustomGroundArmorstand.doTick(CustomGroundArmorstand.java:92) [PetBlocks.jar:?] 06.11 11:41:16 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2107) [patched_1.12.2.jar:git-Paper-1244] 06.11 11:41:16 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1960) [patched_1.12.2.jar:git-Paper-1244] 06.11 11:41:16 [Server] INFO at net.minecraft.server.v1_12_R1.EntityArmorStand.B_(EntityArmorStand.java:564) [patched_1.12.2.jar:git-Paper-1244] 06.11 11:41:16 [Server] INFO at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1752) [patched_1.12.2.jar:git-Paper-1244] 06.11 11:41:16 [Server] INFO at net.minecraft.server.v1_12_R1.World.h(World.java:1722) [patched_1.12.2.jar:git-Paper-1244] 06.11 11:41:16 [Server] INFO at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1543) [patched_1.12.2.jar:git-Paper-1244] 06.11 11:41:16 [Server] INFO at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:675) [patched_1.12.2.jar:git-Paper-1244] 06.11 11:41:16 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:913) [patched_1.12.2.jar:git-Paper-1244] 06.11 11:41:16 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1244] 06.11 11:41:16 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1244] 06.11 11:41:16 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1244] 06.11 11:41:16 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91] 06.11 11:41:16 [Server] WARN Failed to send packet. 06.11 11:41:16 [Server] INFO

**Comment by Shynixn** [comment]
Cannot replicate this issue even when I used PaperSpigot.

**Comment by Shynixn** [comment]
No further replies.
