### ISSUE TITLE
Error on Spigot 1.12.2 using PetBlocks Snapshot.

### ISSUE THREAD

**Issue by TheIntelloBox** [Shynixn/PetBlocks#57]
[23:21:41] [Craft Scheduler Thread - 1213/WARN]: [PetBlocks] Database error occurred.
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such column: pet.engine)
	at org.sqlite.core.DB.newSQLException(DB.java:909) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.sqlite.core.DB.newSQLException(DB.java:921) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.sqlite.core.DB.throwex(DB.java:886) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:127) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.sqlite.core.DB.prepare(DB.java:227) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:41) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:48) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:263) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:235) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at com.zaxxer.hikari.proxy.ConnectionProxy.prepareStatement(ConnectionProxy.java:265) ~[?:?]
	at com.zaxxer.hikari.proxy.HikariConnectionProxy.prepareStatement(HikariConnectionProxy.java) ~[?:?]
	at com.github.shynixn.petblocks.bukkit.lib.ExtensionHikariConnectionContext.executeQuery(ExtensionHikariConnectionContext.java:169) ~[?:?]
	at com.github.shynixn.petblocks.bukkit.lib.ExtensionHikariConnectionContext.executeStoredQuery(ExtensionHikariConnectionContext.java:150) ~[?:?]
	at com.github.shynixn.petblocks.bukkit.logic.persistence.controller.PetDataRepository.getByPlayer(PetDataRepository.java:107) ~[?:?]
	at com.github.shynixn.petblocks.bukkit.logic.business.listener.PetDataListener.lambda$handleChatMessage$14(PetDataListener.java:496) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
[23:21:41] [Craft Scheduler Thread - 1213/WARN]: [PetBlocks] Plugin PetBlocks v6.3.1-SNAPSHOT generated an exception while executing task 1032198
java.lang.NullPointerException: null
	at com.github.shynixn.petblocks.bukkit.logic.persistence.controller.PetDataRepository.getByPlayer(PetDataRepository.java:122) ~[?:?]
	at com.github.shynixn.petblocks.bukkit.logic.business.listener.PetDataListener.lambda$handleChatMessage$14(PetDataListener.java:496) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by Shynixn** [comment]
" SQL error or missing database (no such column: pet.engine)"

Did you upgrade from PetBlocks v6.1.0 or below? This error shouldn't not occur when your database (in your case /plugins/PetBlocks/PetBlocks.db file) is up to date.

Replacing the PetBlocks.db file should fix this issue. (simply rename the PetBlocks.db file and restart the server)

Did your other [issue ](https://github.com/Shynixn/PetBlocks/issues/53) get resolved?

**Comment by frizzbee30** [comment]
Hi, I believe I have the same issue, with an external MySQL db. Does the table need deleting to fix? I have sequentially updated as each version is released.

Thanks

https://pastebin.com/kn8jWaSj

**Comment by Shynixn** [comment]
If you want to have it resolved quickly you can delete the PetBlocks tables. They can be identified by my prefix SHY_<tablename>. However, I'm going to add some lines to the sql script to resolve this problem in next snapshot.

**Comment by Shynixn** [comment]
Should be fixed in latest [snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/petblocks/petblocks-bukkit-plugin/6.4.1-SNAPSHOT/petblocks-bukkit-plugin-6.4.1-20171215.162018-5.jar).

**Comment by Shynixn** [comment]
Added to release v6.4.1
