### ISSUE TITLE
Wrong casting object

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/PetBlocks#59]
[Craft Scheduler Thread - 27/WARN]: [GGMinigame] Plugin GG1 v1.1 generated an exception while executing task 7424
java.lang.ClassCastException: com.github.shynixn.petblocks.bukkit.logic.persistence.entity.PlayerData cannot be cast to com.github.shynixn.petblocks.bukkit.logic.persistence.entity.PetData
    at com.github.shynixn.petblocks.bukkit.logic.persistence.controller.PetDataRepository.store(PetDataRepository.java:57) ~[?:?]
    at com.github.shynixn.petblocks.bukkit.logic.persistence.controller.PetDataRepository.store(PetDataRepository.java:26) ~[?:?]
    at ggetenirya.MainClass$3.run(MainClass.java:136) ~[?:?]
    at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1104]
    at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.11.2.jar:git-Paper-1104]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.11.2.jar:git-Paper-1104]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_141]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_141]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]

**Comment by Shynixn** [comment]
Fixed in latest snapshot petblocks-bukkit-plugin-6.4.0-20171121.175743-2-jar-with-dependencies.jar
