### ISSUE TITLE
petblock call command causes errors

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/PetBlocks#60]
15.11 17:15:06 [Server] ERROR null
15.11 17:15:06 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'petblock call' in com.github.shynixn.petblocks.bukkit.logic.business.commandexecutor.PetDataCommandExecutor(petblock)
15.11 17:15:06 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:160) ~[Paper.jar:git-Paper-1256]
15.11 17:15:06 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:676) ~[Paper.jar:git-Paper-1256]
15.11 17:15:06 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1471) ~[Paper.jar:git-Paper-1256]
15.11 17:15:06 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1276) ~[Paper.jar:git-Paper-1256]
15.11 17:15:06 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper.jar:git-Paper-1256]
15.11 17:15:06 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper.jar:git-Paper-1256]
15.11 17:15:06 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Paper.jar:git-Paper-1256]
15.11 17:15:06 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
15.11 17:15:06 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
15.11 17:15:06 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Paper.jar:git-Paper-1256]
15.11 17:15:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [Paper.jar:git-Paper-1256]
15.11 17:15:06 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [Paper.jar:git-Paper-1256]
15.11 17:15:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [Paper.jar:git-Paper-1256]
15.11 17:15:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [Paper.jar:git-Paper-1256]
15.11 17:15:06 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
15.11 17:15:06 [Server] INFO Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer cannot be cast to org.bukkit.Location
15.11 17:15:06 [Server] INFO at com.github.shynixn.petblocks.bukkit.nms.v1_12_R1.CustomGroundArmorstand.teleport(CustomGroundArmorstand.java:389) ~[?:?]
15.11 17:15:06 [Server] INFO at com.github.shynixn.petblocks.bukkit.logic.business.commandexecutor.PetDataCommandExecutor.onPlayerExecuteCommand(PetDataCommandExecutor.java:43) ~[?:?]
15.11 17:15:06 [Server] INFO at com.github.shynixn.petblocks.bukkit.lib.SimpleCommandExecutor$UnRegistered.execute(SimpleCommandExecutor.java:331) ~[?:?]
15.11 17:15:06 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[Paper.jar:git-Paper-1256]
15.11 17:15:06 [Server] INFO ... 14 more

**Comment by Shynixn** [comment]
Fixed in latest snapshot petblocks-bukkit-plugin-6.4.0-20171121.175743-2-jar-with-dependencies.jar
