### ISSUE TITLE
Whitelist causes player.getWorld to be null

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/PetBlocks#61]
.11 13:10:44 [Server] WARN Cannot create petblock.
16.11 13:10:44 [Server] INFO java.lang.reflect.InvocationTargetException: null
16.11 13:10:44 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
16.11 13:10:44 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
16.11 13:10:44 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
16.11 13:10:44 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
16.11 13:10:44 [Server] INFO at com.github.shynixn.petblocks.bukkit.lib.ReflectionUtils.invokeConstructor(ReflectionUtils.java:95) ~[?:?]
16.11 13:10:44 [Server] INFO at com.github.shynixn.petblocks.bukkit.nms.NMSRegistry.createPetBlock(NMSRegistry.java:71) ~[?:?]
16.11 13:10:44 [Server] INFO at com.github.shynixn.petblocks.bukkit.logic.business.controller.PetBlockRepository.create(PetBlockRepository.java:58) ~[?:?]
16.11 13:10:44 [Server] INFO at com.github.shynixn.petblocks.bukkit.logic.business.listener.PetDataListener.lambda$null$2(PetDataListener.java:187) ~[?:?]
16.11 13:10:44 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [Paper.jar:git-Paper-1256]
16.11 13:10:44 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [Paper.jar:git-Paper-1256]
16.11 13:10:44 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [Paper.jar:git-Paper-1256]
16.11 13:10:44 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [Paper.jar:git-Paper-1256]
16.11 13:10:44 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [Paper.jar:git-Paper-1256]
16.11 13:10:44 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [Paper.jar:git-Paper-1256]
16.11 13:10:44 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
16.11 13:10:44 [Server] INFO Caused by: java.lang.NullPointerException
16.11 13:10:44 [Server] INFO at com.github.shynixn.petblocks.bukkit.nms.v1_12_R1.CustomRabbit.<init>(CustomRabbit.java:34) ~[?:?]
16.11 13:10:44 [Server] INFO at com.github.shynixn.petblocks.bukkit.nms.v1_12_R1.CustomGroundArmorstand.<init>(CustomGroundArmorstand.java:54) ~[?:?]
16.11 13:10:44 [Server] INFO ... 15 more
16.11 13:10:44 [Server] WARN Task #79821 for PetBlocks v6.3.1 generated an exception
16.11 13:10:44 [Server] INFO java.lang.NullPointerException: null
16.11 13:10:44 [Server] INFO at com.github.shynixn.petblocks.bukkit.logic.business.controller.PetBlockRepository.store(PetBlockRepository.java:93) ~[?:?]
16.11 13:10:44 [Server] INFO at com.github.shynixn.petblocks.bukkit.logic.business.controller.PetBlockRepository.store(PetBlockRepository.java:45) ~[?:?]
16.11 13:10:44 [Server] INFO at com.github.shynixn.petblocks.bukkit.logic.business.listener.PetDataListener.lambda$null$2(PetDataListener.java:188) ~[?:?]
16.11 13:10:44 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[Paper.jar:git-Paper-1256]
16.11 13:10:44 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [Paper.jar:git-Paper-1256]
16.11 13:10:44 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [Paper.jar:git-Paper-1256]
16.11 13:10:44 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [Paper.jar:git-Paper-1256]
16.11 13:10:44 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [Paper.jar:git-Paper-1256]
16.11 13:10:44 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [Paper.jar:git-Paper-1256]
16.11 13:10:44 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by Shynixn** [comment]
Fixed in latest snapshot petblocks-bukkit-plugin-6.4.0-20171121.175743-2-jar-with-dependencies.jar
