### ISSUE TITLE
Console error without apparent bug

### ISSUE THREAD

**Issue by BuildABeastWorkshop** [Shynixn/PetBlocks#619]
Not sure what's causing this. There's not any notable errors with the pets that I can see. It's just spamming this in the console repeatedly and being annoying. 

`[06:03:19 ERROR]: [PetBlocks] This is not an error of MCCoroutine! See sub exception for details.
java.util.MissingFormatArgumentException: Format specifier '%2$1s'
        at java.base/java.util.Formatter.format(Formatter.java:2796) ~[?:?]
        at java.base/java.util.Formatter.format(Formatter.java:2728) ~[?:?]
        at java.base/java.lang.String.format(String.java:4390) ~[?:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.impl.commandexecutor.PetBlocksCommandExecutor.setVisibility(PetBlocksCommandExecutor.kt:986) ~[PetBlocks-Premium.jar:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.impl.commandexecutor.PetBlocksCommandExecutor.access$setVisibility(PetBlocksCommandExecutor.kt:36) ~[PetBlocks-Premium.jar:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.impl.commandexecutor.PetBlocksCommandExecutor$commandBuilder$1$21$3.invokeSuspend(PetBlocksCommandExecutor.kt:570) ~[PetBlocks-Premium.jar:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.impl.commandexecutor.PetBlocksCommandExecutor$commandBuilder$1$21$3.invoke(PetBlocksCommandExecutor.kt) ~[PetBlocks-Premium.jar:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.impl.commandexecutor.PetBlocksCommandExecutor$commandBuilder$1$21$3.invoke(PetBlocksCommandExecutor.kt) ~[PetBlocks-Premium.jar:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.lib.com.github.shynixn.mcutils.common.command.ArgumentC.onCommand$common(ArgumentC.kt:53) ~[PetBlocks-Premium.jar:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.lib.com.github.shynixn.mcutils.common.command.CommandBuilder.onCommand(CommandBuilder.kt:160) ~[PetBlocks-Premium.jar:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.lib.com.github.shynixn.mcutils.common.command.CommandBuilder.onCommand(CommandBuilder.kt:158) ~[PetBlocks-Premium.jar:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.lib.com.github.shynixn.mcutils.common.command.CommandBuilder.access$onCommand(CommandBuilder.kt:15) ~[PetBlocks-Premium.jar:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.lib.com.github.shynixn.mcutils.common.command.CommandBuilder$CommandImpl$execute$1.invokeSuspend(CommandBuilder.kt:281) ~[PetBlocks-Premium.jar:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.lib.com.github.shynixn.mcutils.common.command.CommandBuilder$CommandImpl$execute$1.invoke(CommandBuilder.kt) ~[PetBlocks-Premium.jar:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.lib.com.github.shynixn.mcutils.common.command.CommandBuilder$CommandImpl$execute$1.invoke(CommandBuilder.kt) ~[PetBlocks-Premium.jar:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.impl.commandexecutor.PetBlocksCommandExecutor$coroutineExecutor$1$execute$1.invokeSuspend(PetBlocksCommandExecutor.kt:59) ~[PetBlocks-Premium.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367) ~[?:?]
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30) ~[?:?]
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25) ~[?:?]
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110) ~[?:?]
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) ~[?:?]
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[?:?]
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[?:?]
        at com.github.shynixn.mccoroutine.bukkit.MCCoroutineKt.launch(MCCoroutine.kt:93) ~[?:?]
        at com.github.shynixn.mccoroutine.bukkit.MCCoroutineKt.launch$default(MCCoroutine.kt:84) ~[?:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.impl.commandexecutor.PetBlocksCommandExecutor$coroutineExecutor$1.execute(PetBlocksCommandExecutor.kt:58) ~[PetBlocks-Premium.jar:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.lib.com.github.shynixn.mcutils.common.command.CommandBuilder$CommandImpl.execute(CommandBuilder.kt:279) ~[PetBlocks-Premium.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1000) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.impl.service.PetActionExecutionServiceImpl.executeCommandAction(PetActionExecutionServiceImpl.kt:310) ~[PetBlocks-Premium.jar:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.impl.service.PetActionExecutionServiceImpl.executeAction(PetActionExecutionServiceImpl.kt:84) ~[PetBlocks-Premium.jar:?]
        at PetBlocks-Premium.jar/com.github.shynixn.petblocks.impl.service.PetActionExecutionServiceImpl$executeAction$1.invokeSuspend(PetActionExecutionServiceImpl.kt) ~[PetBlocks-Premium.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) ~[?:?]
        at com.github.shynixn.mccoroutine.bukkit.CoroutineTimings.run(CoroutineTimings.kt:38) ~[?:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[06:04:44 INFO]: UUID of player VivaCaligula_ is cd162e8a-a4f5-43b1-8ff2-162166a5aacd`

**Comment by Shynixn** [comment]
This error is caused by an invalid message in your language file (in this case the visibility message). Delete your en_us language file and reload the plugin.
