### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheIntelloBox** [Shynixn/PetBlocks#89]
[00:50:51] [Craft Scheduler Thread - 256/WARN]: [PetBlocks] Plugin PetBlocks v6.4.0 generated an exception while executing task 641628
java.lang.NullPointerException: null
	at com.github.shynixn.petblocks.bukkit.logic.persistence.controller.PetDataRepository.create(PetDataRepository.java:91) ~[PetBlocks%20(1).jar:?]
	at com.github.shynixn.petblocks.bukkit.logic.business.commandexecutor.PetDataCommandExecutor.lambda$onPlayerExecuteCommand$3(PetDataCommandExecutor.java:70) ~[PetBlocks%20(1).jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by Shynixn** [comment]
This issue happens when you have got a config parsing error for the gui item "default appearance". 

I would suggest to update to the latest PetBlocks version v6.4.1 where this error was fixed and replaced by a meaningful message called "Default appearance could not be loaded from the config.yml!".
