### ISSUE TITLE
Entity Ticking NMS error 

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/PetBlocks#90]
java.lang.NullPointerException: Ticking entity
    at com.github.shynixn.petblocks.bukkit.nms.helper.PetBlockHelper.executeMovingSound(PetBlockHelper.java:129)
    at com.github.shynixn.petblocks.bukkit.nms.v1_12_R1.CustomRabbit.dm(CustomRabbit.java:57)
    at net.minecraft.server.v1_12_R1.EntityRabbit.l(EntityRabbit.java:87)
    at net.minecraft.server.v1_12_R1.EntityRabbit.dl(EntityRabbit.java:93)
    at net.minecraft.server.v1_12_R1.EntityRabbit.M(EntityRabbit.java:144)
    at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:670)
    at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2095)
    at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:507)
    at net.minecraft.server.v1_12_R1.EntityAgeable.n(EntityAgeable.java:158)
    at net.minecraft.server.v1_12_R1.EntityAnimal.n(EntityAnimal.java:27)
    at net.minecraft.server.v1_12_R1.EntityRabbit.n(EntityRabbit.java:183)
    at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1944)
    at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246)
    at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631)
    at net.minecraft.server.v1_12_R1.World.h(World.java:1601)
    at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435)
    at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665)
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817)
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
    at java.lang.Thread.run(Thread.java:748)

**Comment by Shynixn** [comment]
https://github.com/Shynixn/PetBlocks/issues/88 #88 

Seems to be the same sound issue.
